name: Deploy static website

on:
  push:
    branches:
      - main
      - dev
      - hml

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
      - name: Deploy static content
        run: ./scripts/deploy.sh .
        env:
          STORAGE_ACCOUNTS: ${{ secrets.STORAGE_ACCOUNTS }}
